### ISSUE TITLE
Tests time out

### ISSUE THREAD

**Issue by chrisgorgo** [bids-apps/afni_proc#1]
Is there some set of options that would limit the processing time to under 2h per participant for the purpose of smoke tests on Circle?

**Comment by Shotgunosine** [comment]
I'd imagine this should run fairly fast:
 -subj_id {subj_id} -script proc.bids -scr_overwrite -out_dir {{out_dir}} -blocks tshift volreg blur scale -copy_anat {{anat_path}} -tcat_remove_first_trs 0 -dsets {{epi_paths}} -volreg_align_to MIN_OUTLIER -blur_size 4.0 -bash
