### ISSUE TITLE
Exception: Unsafe character '{' found in command

### ISSUE THREAD

**Issue by chrisgorgo** [bids-apps/afni_proc#4]
```
docker run -ti --rm bids/afni_proc /bids_dataset /outputs participant --participant_label 01 --afni_proc '-subj_id {subj_id} -script proc.bids -scr_overwrite -out_dir {{out_dir}} -blocks tshift volreg blur scale -copy_anat {{anat_path}} -tcat_remove_first_trs 0 -dsets {{epi_paths}} -volreg_align_to MIN_OUTLIER -blur_size 4.0 -bash'
```

```
Traceback (most recent call last):

  File "/run.py", line 253, in <module>

    raise Exception("Unsafe character '{' found in command: %s"%cmd.join(' '))

Exception: Unsafe character '{' found in command:  
```

See https://circleci.com/gh/BIDS-Apps/afni_proc/9?utm_campaign=build-failed&utm_medium=email&utm_source=notification for more details.

Am I using `--afni_proc` in the wrong way?

**Comment by Shotgunosine** [comment]
No double curly braces in what you pass in. The curly braces get used for string completion. Having double curly braces means that the curly braces end up passed through to the command line, and people could use those to do something naughty, so I'm filtering out any commands with those or a whole bunch of other characters to make it a bit harder for anyone to execute an arbitrary command.

This should work:
`docker run -ti --rm bids/afni_proc /bids_dataset /outputs participant --participant_label 01 --afni_proc '-subj_id {subj_id} -script proc.bids -scr_overwrite -out_dir {out_dir} -blocks tshift volreg blur scale -copy_anat {anat_path} -tcat_remove_first_trs 0 -dsets {epi_paths} -volreg_align_to MIN_OUTLIER -blur_size 4.0 -bash'`

**Comment by chrisgorgo** [comment]
Thanks. The example in the readme needs to be updated than.

**Comment by chrisgorgo** [comment]
I'm getting
```
/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py:2218: FutureWarning: split() requires a non-empty pattern match.

  yield pat.split(line.strip())

/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py:2220: FutureWarning: split() requires a non-empty pattern match.

  yield pat.split(line.strip())

Traceback (most recent call last):

  File "/run.py", line 312, in <module>

    anat_exts = np.array([float(ss) for ss in subprocess.check_output(["3dinfo", "-extent", anat_path]).decode().split('\t')])

  File "/run.py", line 312, in <listcomp>

    anat_exts = np.array([float(ss) for ss in subprocess.check_output(["3dinfo", "-extent", anat_path]).decode().split('\t')])

ValueError: could not convert string to float: 'NO-DSET'
```
with these settings (although I am not sure if it is specific to those or a general bug). More details at https://circleci.com/gh/BIDS-Apps/afni_proc/10
