### ISSUE TITLE
afni_proc concatenates runs across sessions

### ISSUE THREAD

**Issue by chrisgorgo** [bids-apps/afni_proc#5]
Single sessions dataset https://13-113127138-gh.circle-artifacts.com/0/home/ubuntu/outputs1/reports/sub-01_individual.html

Two session dataset https://13-113127138-gh.circle-artifacts.com/0/home/ubuntu/outputs2/reports/sub-02_individual.html

Was this intended?

**Comment by Shotgunosine** [comment]
Yeah, I'm concatenating the runs in the motion report.

**Comment by Shotgunosine** [comment]
We're working on PR #9 to fix this behavior. The behavior is fixed, just need to fix the reporting.
