### ISSUE TITLE
Turn on github pages for gh-pages branch

### ISSUE THREAD

**Issue by Shotgunosine** [bids-apps/afni_proc#7]
Hey Chris, I finished running the example group report with improved alignments. Can you turn on the github pages for this repo's gh-pages branch so I can link to the example group report in the OHBM abstract?

**Comment by chrisgorgo** [comment]
hmmm - gh-pages is up  - check out http://bids-apps.neuroimaging.io/afni_proc/

**Comment by Shotgunosine** [comment]
Okie, thanks! I didn't realize it was enabled by default. I've got a link
to the example report there dropped into the abstract. What else would need
to be done before the app could be deployed to openneuro?

**Comment by chrisgorgo** [comment]
Nicely done! 

Next need to make release on github, this will trigger docker deployment. More info: http://bids-apps.neuroimaging.io/dev_faq/
